import click
import pathlib
import json
from fairscape_cli.models.rocrate import (
    UpdateEntitiesInGraph
)
from fairscape_cli.entailments.inverse import augment_rocrate_with_inverses, EVI_NAMESPACE
from fairscape_cli.entailments.find_outputs import (
    extract_datasets_from_graph,
    extract_samples_from_graph,
    extract_used_datasets_from_computations,
    calculate_inputs_outputs,
    add_inputs_outputs_to_rocrate
)
from fairscape_cli.entailments.summary_stats import (
    build_summary_dataset,
    compute_stats,
    human_size,
    is_dataset,
    is_tabular_entity,
    read_table,
)

@click.group('augment')
def augment_group():
    """Commands to augment and modify existing RO-Crate metadata."""
    pass

@augment_group.command('update-entities')
@click.argument('rocrate-path', type=click.Path(exists=True, path_type=pathlib.Path))
@click.option('--query', 'query_str', required=True, help="MongoDB-style query as a JSON string to select entities.")
@click.option('--update', 'update_str', required=True, help="MongoDB-style update operation as a JSON string.")
@click.pass_context
def update_entities_command(
    ctx,
    rocrate_path: pathlib.Path,
    query_str: str,
    update_str: str
):
    """
    Selects and updates entities within an RO-Crate using MongoDB-like query
    and update operations on the '@graph'.
    """
    try:
        try:
            query_dict = json.loads(query_str)
        except json.JSONDecodeError as e:
            click.echo(f"Error: Invalid JSON in --query string: {e}", err=True)
            ctx.exit(1)
        
        try:
            update_dict = json.loads(update_str)
        except json.JSONDecodeError as e:
            click.echo(f"Error: Invalid JSON in --update string: {e}", err=True)
            ctx.exit(1)
        
        success, message = UpdateEntitiesInGraph(
            rocrate_path,
            query_dict,
            update_dict
        )
        
        if success:
            click.echo(message)
        else:
            click.echo(f"Error: {message}", err=True)
            ctx.exit(1)
    
    except Exception as e:
        click.echo(f"An unexpected error occurred: {type(e).__name__} - {e}", err=True)
        ctx.exit(1)

@augment_group.command('link-inverses')
@click.argument(
    'rocrate-path',
    type=click.Path(path_type=pathlib.Path, exists=True, file_okay=True, dir_okay=True)
)
@click.option(
    '--ontology-path',
    type=click.Path(path_type=pathlib.Path, dir_okay=False),
    default=None,
    help="Path to the OWL ontology file. Defaults to evi.xml in the entailments folder."
)
@click.option(
    '--namespace',
    default=EVI_NAMESPACE,
    show_default=True,
    help="The primary namespace URI used for property keys in JSON."
)
@click.pass_context
def link_inverses_command(
    ctx,
    rocrate_path: pathlib.Path,
    ontology_path: pathlib.Path,
    namespace: str
):
    """
    Augments an RO-Crate by finding owl:inverseOf properties defined in the
    ontology and ensuring both sides of the relationship are present in the
    RO-Crate's JSON-LD metadata.
    """
    if ontology_path is None:
        current_file = pathlib.Path(__file__)
        package_root = current_file.parent.parent
        default_ontology_path = package_root / "entailments" / "evi.xml"
        
        if not default_ontology_path.exists():
            click.echo(f"Error: Default ontology file not found at {default_ontology_path}", err=True)
            click.echo("Please specify --ontology-path explicitly.", err=True)
            ctx.exit(1)
        
        ontology_path = default_ontology_path
    elif not ontology_path.exists():
        click.echo(f"Error: Specified ontology file does not exist: {ontology_path}", err=True)
        ctx.exit(1)
    
    click.echo(f"Augmenting RO-Crate at: {rocrate_path}")
    click.echo(f"Using ontology: {ontology_path}")
    click.echo(f"Primary JSON property namespace: {namespace}")
    
    success = augment_rocrate_with_inverses(
        rocrate_path=rocrate_path,
        ontology_path=ontology_path,
        default_namespace_prefix=namespace
    )
    
    if success:
        pass
    else:
        click.echo("Augmentation failed. See messages above for details.", err=True)
        ctx.exit(1)

@augment_group.command('add-io')
@click.argument('rocrate-path', type=click.Path(exists=True, path_type=pathlib.Path))
@click.option('--verbose', is_flag=True, help="Print detailed information about inputs and outputs")
@click.pass_context
def add_io_command(
    ctx,
    rocrate_path: pathlib.Path,
    verbose: bool
):
    """
    Add EVI:inputs and EVI:outputs to the root dataset of an RO-Crate.
    
    Inputs are:
    - All samples (EVI:Sample entities)
    - Datasets referenced in usedDataset that were not generated by a computation
    - Datasets referenced in usedDataset but not defined in the @graph
    
    Outputs are:
    - All datasets that were not used by any computation
    """
    metadata_path = rocrate_path / "ro-crate-metadata.json"
    
    if not metadata_path.exists():
        click.echo(f"Error: RO-Crate metadata file not found at {metadata_path}", err=True)
        ctx.exit(1)
    
    try:
        with open(metadata_path, 'r') as f:
            metadata = json.load(f)
        
        graph = metadata.get("@graph", [])
        if not graph:
            click.echo("Error: RO-Crate metadata has no @graph", err=True)
            ctx.exit(1)
        
        if verbose:
            click.echo("\n=== Analyzing RO-Crate structure ===")
            
            datasets = extract_datasets_from_graph(graph)
            samples = extract_samples_from_graph(graph)
            used_datasets = extract_used_datasets_from_computations(graph)
            
            click.echo(f"\nFound {len(datasets)} datasets:")
            for dataset_id, has_generated_by in datasets:
                status = "generated" if has_generated_by else "not generated"
                click.echo(f"  - {dataset_id} ({status})")
            
            click.echo(f"\nFound {len(samples)} samples:")
            for sample_id in samples:
                click.echo(f"  - {sample_id}")
            
            click.echo(f"\nFound {len(used_datasets)} used datasets:")
            for used_id in used_datasets:
                click.echo(f"  - {used_id}")
            
            inputs, outputs = calculate_inputs_outputs(graph)
            
            click.echo(f"\n=== Calculated Inputs ({len(inputs)}) ===")
            for inp in inputs:
                click.echo(f"  - {inp['@id']}")
            
            click.echo(f"\n=== Calculated Outputs ({len(outputs)}) ===")
            for out in outputs:
                click.echo(f"  - {out['@id']}")
            
            click.echo("\n=== Updating RO-Crate ===")
        
        success, message = add_inputs_outputs_to_rocrate(rocrate_path)
        
        if success:
            click.echo(message)
        else:
            click.echo(f"Error: {message}", err=True)
            ctx.exit(1)
    
    except json.JSONDecodeError as e:
        click.echo(f"Error parsing JSON: {e}", err=True)
        ctx.exit(1)
    except Exception as e:
        click.echo(f"An unexpected error occurred: {type(e).__name__} - {e}", err=True)
        ctx.exit(1)


@augment_group.command('summary-stats')
@click.argument('rocrate-path', type=click.Path(exists=True, path_type=pathlib.Path))
@click.option('--id', 'entity_id', default=None, help="Compute stats only for this Dataset @id. Default: every tabular Dataset.")
@click.option('--overwrite/--skip-existing', default=False, help="Recompute stats for Datasets that already have hasSummaryStatistics. Default: skip.")
@click.option('--http-timeout', default=60, show_default=True, help="HTTP timeout in seconds for remote contentUrls.")
@click.option('--dry-run', is_flag=True, help="Print what would change without writing ro-crate-metadata.json.")
@click.pass_context
def summary_stats_command(
    ctx,
    rocrate_path: pathlib.Path,
    entity_id: str,
    overwrite: bool,
    http_timeout: int,
    dry_run: bool,
):
    """
    Compute row/column counts plus per-column statistics for tabular Datasets
    in an RO-Crate. For each matched Dataset:

      * read its contentUrl (local path, file://, or http(s)://) as csv/tsv/parquet
      * populate rowCount / columnCount / contentSize / sampleSize on the source
      * append a child SummaryStats Dataset (per-column dtype, null counts, and
        numeric min/max/mean/std) and link it via hasSummaryStatistics

    For a no-extra-deps row+column counter that works on csv/tsv only, use
    `Dataset.add_summary_stats()` from fairscape_models directly.
    """
    crate_root = rocrate_path if rocrate_path.is_dir() else rocrate_path.parent
    metadata_path = crate_root / "ro-crate-metadata.json"
    if not metadata_path.exists():
        click.echo(f"Error: RO-Crate metadata file not found at {metadata_path}", err=True)
        ctx.exit(1)

    with metadata_path.open("r") as f:
        metadata = json.load(f)

    graph = metadata.get("@graph") or []
    if not graph:
        click.echo("Error: RO-Crate metadata has no @graph", err=True)
        ctx.exit(1)

    root_dataset = graph[1] if len(graph) > 1 else None
    new_entities: list = []
    updated_count = 0
    skipped: list = []

    for entity in graph:
        if not is_dataset(entity):
            continue
        if entity_id and entity.get("@id") != entity_id:
            continue
        if entity is root_dataset:
            continue
        if not is_tabular_entity(entity):
            skipped.append((entity.get("@id"), "not tabular"))
            continue
        if entity.get("hasSummaryStatistics") and not overwrite:
            skipped.append((entity.get("@id"), "already has hasSummaryStatistics (use --overwrite)"))
            continue
        content_url = entity.get("contentUrl")
        if isinstance(content_url, list):
            content_url = content_url[0] if content_url else None
        if not content_url:
            skipped.append((entity.get("@id"), "no contentUrl"))
            continue

        try:
            df, size_bytes, source_desc = read_table(content_url, crate_root, http_timeout=http_timeout)
        except Exception as e:
            click.echo(f"  ! {entity.get('@id')}: failed to read ({type(e).__name__}: {e})", err=True)
            skipped.append((entity.get("@id"), f"read failed: {e}"))
            continue

        rows, cols = int(df.shape[0]), int(df.shape[1])
        size_str = human_size(size_bytes)
        per_column = compute_stats(df)

        entity["rowCount"] = rows
        entity["columnCount"] = cols
        entity["contentSize"] = size_str
        entity.setdefault("sampleSize", rows)

        stats_entity = build_summary_dataset(entity, rows, cols, size_str, per_column)
        entity["hasSummaryStatistics"] = {"@id": stats_entity["@id"]}
        new_entities.append(stats_entity)
        updated_count += 1
        click.echo(f"  ✓ {entity['@id']} ← {rows} rows × {cols} cols, {size_str} (source: {source_desc})")

    if not updated_count:
        click.echo("No Datasets updated.")
        for eid, reason in skipped:
            click.echo(f"  - {eid}: {reason}")
        return

    if new_entities and root_dataset is not None:
        root_dataset.setdefault("hasPart", []).extend([{"@id": e["@id"]} for e in new_entities])
        graph.extend(new_entities)

    if dry_run:
        click.echo(f"\nDRY RUN — would update {updated_count} dataset(s) and add {len(new_entities)} SummaryStats entit{'y' if len(new_entities) == 1 else 'ies'}.")
        return

    with metadata_path.open("w") as f:
        json.dump(metadata, f, indent=2)
    click.echo(f"\nUpdated {updated_count} dataset(s); appended {len(new_entities)} SummaryStats entit{'y' if len(new_entities) == 1 else 'ies'} to {metadata_path}.")
    if skipped:
        click.echo("Skipped:")
        for eid, reason in skipped:
            click.echo(f"  - {eid}: {reason}")