# Project Information
site_name: FAIRSCAPE CLI
site_description: A utility for packaging objects and validating metadata for FAIRSCAPE.
site_url: https://github.com/fairscape/fairscape-cli

# Repository
repo_name: fairscape/fairscape-cli
repo_url: https://github.com/fairscape/fairscape-cli

# Copyright
copyright: Copyright &copy; 2023 THE RECTOR AND VISITORS OF THE UNIVERSITY OF VIRGINIA

# Page tree
nav:
  - Home: index.md
  - Setup: setup.md
  - Getting Started: getting-started.md
  - Examples:
      - Complete Demo: workflows/complete-demo.md
  - Commands:
      - RO-Crate: commands/rocrate.md
      - Schema: commands/schema.md
      - Validation: commands/validate.md
      - Import: commands/import.md
      - Build: commands/build.md
      - Release: commands/release.md
      - Publishing: commands/publish.md

theme:
  name: readthedocs
  navigation_depth: 4

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fairscape/fairscape-cli
