#!/bin/bash

rm -rf tests/test_crates/*

# variables for test
CRATE_NAME="BuildTestCrate"
CRATE_GUID="ark:99999/BUILDTESTCRATE"
CRATE_PATH="./tests/test_crates/build_test_rocrate"
CRATE_ORG_NAME="UVA"
CRATE_PROJ_NAME="B2AI"


# create a test ROCrate
fairscape-cli rocrate create \
        --guid $CRATE_GUID \
        --name $CRATE_NAME \
        --organization-name $CRATE_ORG_NAME \
        --project-name $CRATE_PROJ_NAME \
        --description "example RO crate for testing" \
        --keywords "test" \
        --keywords "example" \
        $CRATE_PATH

# Broken example from Chris
#fairscape-cli rocrate add software --name 'some tool' --description 'A tool to do something' --author 'bob smith' --version 0.1.0 --file-format .py --url https://github.com/someuser/somerepo `pwd`

# add a test dataset 

DATASET_GUID="ARK:APMS_embedding.MuSIC.1/5b3793b6-2bd0-4c51-9f35-c5cd7ddd366c.csv"
DATASET_NAME="AP-MS embeddings"
DATASET_AUTHOR="Gygi lab (https://gygi.hms.harvard.edu/team.html)"
DATASET_DATE_PUB="2021-04-23"
DATASET_DESCRIPTION="Affinity purification mass spectrometer (APMS) embeddings for each protein in the study,  generated by node2vec predict."
DATASET_ASSOC_PUB="Qin, Y. et al. A multi-scale map of cell structure fusing protein images and interactions"
DATASET_ADD_DOC="https://idekerlab.ucsd.edu/music/"
DATASET_SOURCE_PATH="./tests/data/APMS_embedding_MUSIC.csv"
DATASET_DEST_PATH="$CRATE_PATH/APMS_embedding_MUSIC.csv"

fairscape-cli rocrate add dataset \
        --name "$DATASET_NAME" \
        --guid "$DATASET_GUID" \
        --description "$DATASET_DESCRIPTION" \
        --keywords "example" \
        --keywords "test" \
        --date-published "$DATASET_DATE_PUB" \
        --author "$DATASET_AUTHOR" \
        --version '1.0.0' \
        --associated-publication "$DATASET_ASSOC_PUB" \
        --additional-documentation "$DATASET_ADD_DOC" \
        --data-format 'CSV' \
        --source-filepath "$DATASET_SOURCE_PATH" \
        --destination-filepath "$DATASET_DEST_PATH" \
        $CRATE_PATH
 
# add a test software
SOFTWARE_GUID="ark:59853/UVA/B2AI/rocrate_test/music_software"
SOFTWARE_NAME="MuSIC"
SOFTWARE_AUTHOR="Qin, Y."
SOFTWARE_VERSION="1.0"
SOFTWARE_DESCRIPTION="script written in python to calibrate pairwise distance."
SOFTWARE_DATA_FORMAT=".py"
SOFTWARE_DATE_PUB="2021-06-20"
SOFTWARE_SOURCE_FILEPATH="./tests/data/calibrate_pairwise_distance.py"
SOFTWARE_DEST_FILEPATH="$CRATE_PATH/calibrate_pairwise_distance.py"


fairscape-cli rocrate add software \
        --guid "$SOFTWARE_GUID" \
        --name "$SOFTWARE_NAME" \
        --author "$SOFTWARE_AUTHOR" \
        --version "$SOFTWARE_VERSION" \
        --description "$SOFTWARE_DESCRIPTION" \
        --keywords "test" \
        --keywords "example" \
        --file-format "$SOFTWARE_DATA_FORMAT" \
        --date-modified "$SOFTWARE_DATE_PUB" \
        --source-filepath "$SOFTWARE_SOURCE_FILEPATH" \
        --destination-filepath "$SOFTWARE_DEST_FILEPATH" \
        $CRATE_PATH
        
# add a test computation 

fairscape-cli rocrate register computation \
        --guid "ark:59853/UVA/B2AI/rocrate_test/music_test_run" \
        --name "test_computation_name" \
        --run-by "Max Levinson" \
        --date-created "03-17-2023" \
        --description "test run of music pipeline using example data" \
        --keywords "test" \
        --keywords "example" \
        --command "wingardium leviosa" \
        --used-software "$SOFTWARE_GUID" \
        --used-dataset "IF_emd_1_APMS_emd_1.RF_maxDep_30_nEst_1000.fold_1.pkl" \
        --generated "https://github.com/idekerlab/MuSIC/blob/master/Examples/MuSIC_predicted_proximity.txt" \
        $CRATE_PATH


# test rocrate init functionality

# add existing data to a new test path
mkdir tests/test_crates/init_crate
cp tests/data/APMS_embedding_MUSIC.csv tests/test_crates/init_crate/

# initialize a crate in the new directory
