#!/bin/bash


#####################################
#       TEST TABULAR VALIDATION     #
#####################################

SCHEMA_PATH="./tests/test_generated/schema_apms_music_embedding.json"

# clear the schema path
rm $SCHEMA_PATH

fairscape-cli schema create-tabular \
    --name "APMS Embedding Schema" \
    --description "Tabular format for APMS music embeddings from PPI networks from the music pipeline from the B2AI Cellmaps for AI project" \
    --seperator "," \
    --header False \
    $SCHEMA_PATH

fairscape-cli schema add-property string \
    --name 'Experiment Identifier' \
    --index 0 \
    --description 'Identifier for the APMS experiment responsible for generating the raw PPI used to create this embedding vector' \
    --pattern 'APMS_[0-9]*' \
    $SCHEMA_PATH

fairscape-cli schema add-property string \
    --name 'Gene Symbol' \
    --index 1 \
    --description 'Gene Symbol for the APMS bait protien' \
    --pattern '[A-Z0-9]*' \
    --value-url 'http://edamontology.org/data_1026' \
    $SCHEMA_PATH


fairscape-cli schema add-property array \
    --name 'MUSIC APMS Embedding' \
    --index '2::' \
    --description 'Embedding Vector values for genes determined by running node2vec on APMS PPI networks. Vector has 1024 values for each bait protien' \
    --items-datatype 'number' \
    --unique-items False \
    --min-items 1024 \
    --max-items 1024 \
    $SCHEMA_PATH


fairscape-cli schema validate \
    --data ./tests/data/APMS_embedding_MUSIC.csv \
    --schema $SCHEMA_PATH

# test intentional failure of validation
# - Row 1: break regex of the string
# - Row 2: gene name is empty    
# - Row 3: incorrect array length too short    
# - Row 4: added a string value to the numeric array    
# - Row 5: incorrect array lenght too long   
# - Row 6: multiple errors, experiment identifier breaks regex, gene name has characters not allowed, embedding has incorrect types
fairscape-cli schema validate \
    --data ./tests/data/APMS_embedding_corrupted.csv \
    --schema $SCHEMA_PATH


#################################################
#            TEST RO-CRATE FUNCTIONALITY        #
#################################################

# clear previously generated tests
rm -rf ./tests/test_generated/test_crates/*

# variables for test
CRATE_NAME="BuildTestCrate"
CRATE_GUID="ark:99999/BUILDTESTCRATE"
CRATE_PATH="./tests/test_generated/test_crates/build_test_rocrate"
CRATE_ORG_NAME="UVA"
CRATE_PROJ_NAME="B2AI"


# create a test ROCrate
fairscape-cli rocrate create \
        --guid $CRATE_GUID \
        --name $CRATE_NAME \
        --organization-name $CRATE_ORG_NAME \
        --project-name $CRATE_PROJ_NAME \
        --description "example RO crate for testing" \
        --keywords "test" \
        --keywords "example" \
        $CRATE_PATH

# add a test dataset 
DATASET_GUID="ARK:APMS_embedding.MuSIC.1/5b3793b6-2bd0-4c51-9f35-c5cd7ddd366c.csv"
DATASET_NAME="AP-MS embeddings"
DATASET_AUTHOR="Gygi lab (https://gygi.hms.harvard.edu/team.html)"
DATASET_DATE_PUB="2021-04-23"
DATASET_DESCRIPTION="Affinity purification mass spectrometer (APMS) embeddings for each protein in the study,  generated by node2vec predict."
DATASET_ASSOC_PUB="Qin, Y. et al. A multi-scale map of cell structure fusing protein images and interactions"
DATASET_ADD_DOC="https://idekerlab.ucsd.edu/music/"
DATASET_SOURCE_PATH="./tests/data/APMS_embedding_MUSIC.csv"
DATASET_DEST_PATH="$CRATE_PATH/APMS_embedding_MUSIC.csv"

fairscape-cli rocrate add dataset \
        --name "$DATASET_NAME" \
        --guid "$DATASET_GUID" \
        --description "$DATASET_DESCRIPTION" \
        --keywords "example" \
        --keywords "test" \
        --date-published "$DATASET_DATE_PUB" \
        --author "$DATASET_AUTHOR" \
        --version '1.0.0' \
        --associated-publication "$DATASET_ASSOC_PUB" \
        --additional-documentation "$DATASET_ADD_DOC" \
        --data-format 'CSV' \
        --source-filepath "$DATASET_SOURCE_PATH" \
        --destination-filepath "$DATASET_DEST_PATH" \
        $CRATE_PATH
 
# add a test software
SOFTWARE_GUID="ark:59853/UVA/B2AI/rocrate_test/music_software"
SOFTWARE_NAME="MuSIC"
SOFTWARE_AUTHOR="Qin, Y."
SOFTWARE_VERSION="1.0"
SOFTWARE_DESCRIPTION="script written in python to calibrate pairwise distance."
SOFTWARE_DATA_FORMAT=".py"
SOFTWARE_DATE_PUB="2021-06-20"
SOFTWARE_SOURCE_FILEPATH="./tests/data/calibrate_pairwise_distance.py"
SOFTWARE_DEST_FILEPATH="$CRATE_PATH/calibrate_pairwise_distance.py"


fairscape-cli rocrate add software \
        --guid "$SOFTWARE_GUID" \
        --name "$SOFTWARE_NAME" \
        --author "$SOFTWARE_AUTHOR" \
        --version "$SOFTWARE_VERSION" \
        --description "$SOFTWARE_DESCRIPTION" \
        --keywords "test" \
        --keywords "example" \
        --file-format "$SOFTWARE_DATA_FORMAT" \
        --date-modified "$SOFTWARE_DATE_PUB" \
        --source-filepath "$SOFTWARE_SOURCE_FILEPATH" \
        --destination-filepath "$SOFTWARE_DEST_FILEPATH" \
        $CRATE_PATH
        
# add a test computation 

fairscape-cli rocrate register computation \
        --guid "ark:59853/UVA/B2AI/rocrate_test/music_test_run" \
        --name "test_computation_name" \
        --run-by "Max Levinson" \
        --date-created "03-17-2023" \
        --description "test run of music pipeline using example data" \
        --keywords "test" \
        --keywords "example" \
        --command "wingardium leviosa" \
        --used-software "$SOFTWARE_GUID" \
        --used-dataset "IF_emd_1_APMS_emd_1.RF_maxDep_30_nEst_1000.fold_1.pkl" \
        --generated "https://github.com/idekerlab/MuSIC/blob/master/Examples/MuSIC_predicted_proximity.txt" \
        $CRATE_PATH

############################################
#                ROCRATE INIT              #
############################################ 

# add existing data to a new test path
INIT_CRATE_PATH="./tests/data/test_generated/init_crate/"
INIT_CRATE_DATASET_PATH="APMS_embedding_MUSIC.csv"

mkdir $INIT_CRATE_PATH
cp tests/data/APMS_embedding_MUSIC.csv $INIT_CRATE_PATH

cd $INIT_CRATE_PATH

# initialize a crate in the new directory
fairscape-cli rocrate init \
        --guid $CRATE_GUID \
        --name $CRATE_NAME \
        --organization-name $CRATE_ORG_NAME \
        --project-name $CRATE_PROJ_NAME \
        --description "example RO crate for testing" \
        --keywords "test" \
        --keywords "example" 


fairscape-cli rocrate register dataset \
        --name "$DATASET_NAME" \
        --guid "$DATASET_GUID" \
        --description "$DATASET_DESCRIPTION" \
        --keywords "example" \
        --keywords "test" \
        --date-published "$DATASET_DATE_PUB" \
        --author "$DATASET_AUTHOR" \
        --version '1.0.0' \
        --associated-publication "$DATASET_ASSOC_PUB" \
        --additional-documentation "$DATASET_ADD_DOC" \
        --data-format 'CSV' \
        --filepath "$INIT_CRATE_DATASET_PATH" \
        .


fairscape-cli rocrate register software \
        --guid "$SOFTWARE_GUID" \
        --name "$SOFTWARE_NAME" \
        --author "$SOFTWARE_AUTHOR" \
        --version "$SOFTWARE_VERSION" \
        --description "$SOFTWARE_DESCRIPTION" \
        --keywords "test" \
        --keywords "example" \
        --file-format "$SOFTWARE_DATA_FORMAT" \
        --date-modified "$SOFTWARE_DATE_PUB" \
        .



