FROM python:3.11:latest

RUN apt update -y && apt install curl git 
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.13.1

# add to ~/.bashrc
RUN echo  '. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc

# Install Python plugin for asdf:
RUN asdf plugin-add python

# List all available Python interpreters:
# asdf list-all python

# Install the Python interpreters that you need:
RUN asdf install python 3.11.6
RUN asdf install python 3.10.13
RUN asdf install python 3.9.18
RUN asdf install python 3.8.17

RUN asdf remove python 3.11.6
# run tests with current version
# set local version
## asdf local <name> <version> [<version>...]
## asdf exec <command> [args...]